import { type ColumnDef } from "@tanstack/react-table";

export type Column = {
  id?: string;
  name: string;
  type: string;
  constraint: number | null;
  nullable?: boolean;
  position?: number;
  primaryKey: boolean;
  autogenerated?: boolean;
  optional?: any;
};

export type Table = {
  id: string;
  name: string;
  columns: Column[];
};

export type Database = {
  id: string;
  name: string;
  tables: Table[];
};

export type DataOptions = {
  page: number;
  pages: number;
  returned: number;
  limit: number;
};

export type FilterOption = {
  id: string;
  column: string;
  operator: string;
  combineWith: string;
  value: any | undefined | null;
};

export type SortingOption = {
  id: string;
  column: string;
  ascending: boolean;
};

export type ProjectionOption = {
  id: string;
  column: string;
};

export type CustomColumnDef<TData, TValue> = ColumnDef<TData, TValue> & {
  className?: string;
  customComponent?: React.ReactElement;
};

// ============================================================
// Dashboard Types
// ============================================================

// --- Filters ---

export interface DashboardFilters {
  dateRange: { from: string; to: string };
  facilityCode?: string;
  projectId?: string;
  useCaseId?: string;
  database: "openldr" | "openldr_external";
}

export type DatePreset = "today" | "7d" | "30d" | "90d" | "1y" | "custom";

// --- KPI / Stat Cards ---

export interface DashboardKPI {
  totalPatients: number;
  totalLabRequests: number;
  totalLabResults: number;
}

// --- Lab Activity Over Time ---

export interface LabActivityPoint {
  timestamp: string; // ISO date string
  requests: number;
  results: number;
}

// --- Specimen Type Distribution ---

export interface SpecimenTypeCount {
  specimenType: string;
  label: string;
  count: number;
  percentage: number;
}

// --- Test Panel Volume ---

export interface TestPanelVolume {
  panelCode: string;
  panelDesc: string;
  count: number;
}

// --- Result Flag Distribution ---

export interface ResultFlagCount {
  flag: string; // e.g. "N", "H", "L", "A", "R", "S"
  label: string; // e.g. "Normal", "High", "Low", "Abnormal", "Resistant", "Susceptible"
  count: number;
  color: string;
}

// --- Facility Activity ---

export interface FacilityActivity {
  facilityCode: string;
  facilityName: string;
  countryCode: string;
  requestCount: number;
  resultCount: number;
  patientCount: number;
  latitude?: number;
  longitude?: number;
}

// --- Data Pipeline ---

export interface PipelineStageCount {
  stage: "raw" | "validated" | "mapped" | "processed";
  label: string;
  count: number;
  color: string;
}

// --- Service Health ---

export type ServiceStatus = "healthy" | "degraded" | "down" | "unknown";

export interface ServiceHealth {
  name: string;
  displayName: string;
  status: ServiceStatus;
  responseTimeMs?: number;
  uptime?: string;
  version?: string;
  details?: Record<string, string | number>;
}

// --- Storage (MinIO) ---

export interface StorageOverview {
  totalBuckets: number;
  totalObjects: number;
  totalSizeBytes: number;
  usedSizeBytes: number;
  buckets: BucketInfo[];
}

export interface BucketInfo {
  name: string;
  objectCount: number;
  sizeBytes: number;
  createdAt: string;
}

// --- Database Stats ---

export interface DatabaseStats {
  name: string;
  sizeBytes: number;
  tableCount: number;
  activeConnections: number;
  maxConnections: number;
  uptime: string;
  tables: TableStats[];
}

export interface TableStats {
  tableName: string;
  rowCount: number;
  sizeBytes: number;
  indexSizeBytes: number;
}

// --- Recent Lab Results (table) ---

export interface RecentLabResult {
  labResultsId: string;
  requestId: string;
  facilityName: string;
  patientId: string;
  panelDesc: string;
  observationDesc: string;
  rptResult: string;
  rptUnits: string;
  rptFlag: string;
  resultTimestamp: string;
}

// --- Aggregated Dashboard State ---

export interface DashboardData {
  kpi: DashboardKPI;
  labActivity: LabActivityPoint[];
  specimenDistribution: SpecimenTypeCount[];
  testPanelVolume: TestPanelVolume[];
  resultFlagDistribution: ResultFlagCount[];
  facilityActivity: FacilityActivity[];
  pipeline: PipelineStageCount[];
  services: ServiceHealth[];
  storage: StorageOverview;
  databases: DatabaseStats[];
  recentResults: RecentLabResult[];
}
